### ISSUE TITLE
No avatar shown with GNUSocial 1.2.0-beta4

### ISSUE THREAD

**Issue by strk** [chimo/gs-libravatar#1]
The avatar doesn't show up. I verified `$avatar->url` being set correctly but it's not used.
@chimo found out the breaking upstream commit being https://git.gnu.io/gnu/gnu-social/commit/1a1e44cdfde155279e3890c20963b5dbb9d6a0ea

**Comment by chimo** [comment]
Hi,

Just pushed some changes. Give it a try whenever you have a chance and let me know if it works for you.

Seems to be working on my end.

**Comment by strk** [comment]
Works for me too. Thanks!
